### ISSUE TITLE
CRC-64/XZ not CRC-64/ECMA-182

### ISSUE THREAD

**Issue by AlexanderOMara** [akiver/crc64-ecma#2]
Just a heads up, this library appears to implement CRC-64/XZ and not CRC-64/ECMA-182.

Apparently [CRC-64/XZ](https://reveng.sourceforge.io/crc-catalogue/17plus.htm#crc.cat.crc-64-xz) is often confused with [CRC-64/ECMA-182](https://reveng.sourceforge.io/crc-catalogue/17plus.htm#crc.cat-bits.64) for some reason.

**Comment by akiver** [comment]
Thanks for the notice!
I added a note about it in the readme - I used the [wikipedia](https://en.wikipedia.org/wiki/Cyclic_redundancy_check) page as a reference and, indeed, it's confusing.
